### PR TITLE
TASK: Set requirements to work with neos 5

### PR DESCRIPTION
**Pull request by Lemmork**

### CODE REVIEW

**Comment by Benjamin-K** [comment]
Thanks for your pull request. Two questions about it:

1. Did you test the update to work with Neos 5?
2. Can you please update the composer.json to still work with Neos 4 so any further updates on this package will work for Neos 4 and 5?

**Comment by Lemmork** [comment]
I tested it with neos5.
Not sure if it will work for both versions, because requirement neos/form version 5 will not work with neos 4. Perhaps it should be a major version release?

**Comment by Lemmork** [comment]
You are right, there is no need to fix the version for neos/form to version 5. I changed it to have compatibility with 4 and 5.

**Comment by Benjamin-K** [comment]
Thanks again. This will help many people i think.

**Pull request merged**
