### PR TITLE
[BUGFIX] Fix recaptcha timeout issue

### PR DESCRIPTION
**Pull request by fanat98**

### CODE REVIEW

**Comment by fanat98** [comment]
Hello Benjamin,

There seems to be a problem with recapcha3 .
(https://stackoverflow.com/questions/55251837/how-to-solve-google-v3-recaptcha-timeout/58762647#58762647)
The token expires after 2 minutes, you have to run this code.

For example if a form wasn't sent before the 2 minutes, it won't work.

Best regards
aslam

**Comment by lorenzulrich** [comment]
@Benjamin-K We had this problem with several customers. as @fanat98 told, it's really easy to reproduce: Open a form, fill some values, wait for 2 minutes and then try submitting. You will get an error.

**Comment by Benjamin-K** [comment]
OK, Sounds reasonable. Could you change your line a little to
```setInterval(grecaptchaOnload, 110000);```
to reduce size? I will merge it then.
Thx for your PR.

**Comment by Benjamin-K** [comment]
Thx, i merged your PR and tagged a new release.

**Pull request merged**
