### PR TITLE
Fix siteKey rendering for script src

### LINKED ISSUE #13: SiteKey rendering for reCAPTCHA v3
Currently there is a bug while rendering the SiteKey into the scr of the API Script.

This is caused by the curly brackets of the JavaScript function, colliding with the brackets rendering the siteKey. `{element.properties.siteKey}`

A possible solution would be to use the `<f:format.raw>` ViewHelper.
Another solution would be to render the key outside of the function, or just use the earlier defined siteKey variable.

Tried with Neos version: 4.3.7 and dev-master version of this package.

### PR DESCRIPTION
**Pull request by derweba**
Explanation and alternative solutions in #13.
Closes #13

### CODE REVIEW

**Comment by Benjamin-K** [comment]
Hello @derweba 
Thanks for your pull request. Did you test your solution/changes? If it works, i will merge your pull request and create a new release.

**Comment by derweba** [comment]
Hello @Benjamin-K 
Yes, i tested this solution with Neos 4.3.7 and it works.
A new release would be great.

**Comment by derweba** [comment]
Hey @Benjamin-K,
Do you have any news on the status of merging this pull request? Would be great if you could merge this. Thanks :)

**Comment by Benjamin-K** [comment]
Hey @derweba,
i have merged your changes and created a new release. Thanks for your participation.

**Pull request merged**
